### ISSUE TITLE
关于G2和G3的区别？

### ISSUE THREAD

**Issue by Xiaoning1943** [traas-stack/altershield#10]
关于变更代际，G3阶段的描述是在G2（有完整的变更工单）基础上，增加了变更提单阶段的感知。
想问下，“变更提单阶段”具体是指什么呢？

**Comment by jinyalong** [comment]
基于OCMS的定义，整个变更单会拆分为多个执行单，目的是分批次执行变更降低变更引发的风险。而变更提单阶段指的是整个变更声明周期的工单对象，更细粒度的则是执行单维度（批次单）。
