### ISSUE TITLE
有微信交流群吗？看官网的链接二维码过期了

### ISSUE THREAD

**Issue by z7658329** [traas-stack/altershield#13]
[有微信交流群吗？看官网的链接二维码过期了](https://altershield.io/zh-CN/blog/meetup-0710#%E5%8A%A0%E5%85%A5%E6%88%91%E4%BB%AC)

**Comment by BootstrapperSBL** [comment]
可以先加钉钉群，微信二维码有比较短的有效期，且超过200人就无法扫码。
![image](https://github.com/traas-stack/altershield/assets/131545713/cc33b9f4-3637-4d5e-933c-8e92e012e6c3)

**Comment by simops-328** [comment]
这个钉钉群也超了100人了没法加入了
